# CMSC 331 Spring 2021
### Instructor: Fereydoon Vafaei

<br>

## <font color='blue'>Numpy Array Slicing</font>

Numpy is an effective Python library to work with arrays. In this notebook, let's practice a few numpy array slicing exercises.

First, create a 1D numpy array with evenly placed integer numbers (type=np.float64) over a specified interval.

In [ ]:
import numpy as np

In [1]:
x = np.linspace(1,10, num=10)
print(type(x))      # numpy.ndarray
print(type(x[0]))   # numpy.float64
x

<class 'numpy.ndarray'>
<class 'numpy.float64'>


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Now, there are different ways that you may want to slice this numpy array. In the following cells, see some examples.

Let's slice the first five elements. The generic format for slicing is: `[start:stop:step]` 
Notice that indices start from `0`.
Also notice that specifying the `step` is optional, the default `step = 1`

- If we don't pass `start`, it's considered 0

- If we don't pass `stop`, it's considered the elements from `start` to the end of the array
- If we don't pass `step`, it's considered 1

In [2]:
x[0:5]

array([1., 2., 3., 4., 5.])

In [3]:
x[0:5:2]

array([1., 3., 5.])

In [4]:
x[1:7:2]

array([2., 4., 6.])

> We can also leave the index before `:` blank. This means slice everything from the beginning till the stop index - i.e. the index after `:`, excluding `x[5]`.

In [5]:
x[:5]	    # [1,2,3,4,5]

array([1., 2., 3., 4., 5.])

In [6]:
# The index of the 5th element is 4
x[4]

5.0

In [7]:
x[5]

6.0

> And similarly for slicing anything from the index before `:` till the end - this time though the slice includes `x[5]` itself.

In [8]:
x[5:]

array([ 6.,  7.,  8.,  9., 10.])

> Some more examples:

In [9]:
x[0:]	    # the entire array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
print(x[:0])      # Early stopping means the returned slice is empty!

[]


In [11]:
print(x[:-1])     # all excluding the last element

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
print(x[-1:])      # Only the last element

[10.]


In [13]:
print(x[-4:-1])    # negative indexing 

[7. 8. 9.]


In [14]:
print(x[::-1])      # all in the reversed order

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [15]:
print(x[0:10:2])    # step=2 : [1,3,5,7,9]

[1. 3. 5. 7. 9.]


In [16]:
print(x[::2])       # [1,3,5,7,9]

[1. 3. 5. 7. 9.]


## 2D Arrays

Now, let's try some 2D arrays.

In [11]:
# 2-dimensional np.array slicing with comma (tuple indices)
a = np.reshape(np.arange(9),(3,3)) # create a 2D array 3x3 with numbers {0..8}
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(a[0,:])       # first row

[0 1 2]


In [13]:
print(a[:,0])       # first column displayed horizontally

[0 3 6]


In [14]:
print(a[0:,0:1])    # first column displayed vertically (in 3 rows)

[[0]
 [3]
 [6]]


In [15]:
print(a[:3,:1])     # another way to print the first column vertically (in 3 rows)

[[0]
 [3]
 [6]]


>In general, to slice 2d arrays, open/close brackets, then put a comma between the two colons `[:,:]` then:
- either replace each colon with a number to get a specific row or column, e.g `[2,:]` --> would return the third row
- or specify the range of rows/cols with the colon in between, e.g `[:,0:2]` --> would return the first two columns

>Let's see how it works.

In [16]:
a[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(a[0:2,])      # first two rows, also can be written as a[0:2,:]

[[0 1 2]
 [3 4 5]]


In [18]:
print(a[:,0:2])     # first two columns

[[0 1]
 [3 4]
 [6 7]]


> The following though is not a valid syntax!

In [19]:
a[,0:2] 	    # invalid syntax

SyntaxError: invalid syntax (<ipython-input-19-f0611a762ed9>, line 1)

> Now see the output of the following interesting 2D slices:

In [28]:
print('first and third row (step=2) \n', a[:3:2,:])    # first and third row (step=2)
print('first and third column (step=2) \n', a[:,0:3:2])   # first and third column (step=2)
print('first row reversed', a[0, ::-1])  # first row reversed
print('first column reversed', a[::-1, 0])  # first column reversed
print('column-wise reverse or row-shift \n', a[::-1, ::])      # this reverses the elements in each column, i.e. column-wise reverse or row-shift
print('row-wise reverse or column-shift \n', a[::, ::-1])   # this reverses the elements in each row, i.e. row-wise reverse or colomn-shift
print('2D reverse \n', a[::-1,::-1]) # this reverses both axes

first and third row (step=2) 
 [[0 1 2]
 [6 7 8]]
first and third column (step=2) 
 [[0 2]
 [3 5]
 [6 8]]
first row reversed [2 1 0]
first column reversed [6 3 0]
column-wise reverse or row-shift 
 [[6 7 8]
 [3 4 5]
 [0 1 2]]
row-wise reverse or column-shift 
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
2D reverse 
 [[8 7 6]
 [5 4 3]
 [2 1 0]]


> Indexing and slicing for Python lists have differences.

In [27]:
b = [[0,1,2], [3,4,5]]
print(type(b))      # list
b

<class 'list'>


[[0, 1, 2], [3, 4, 5]]

In [28]:
print(b[:1])
print(b[-1])

[[0, 1, 2]]
[3, 4, 5]


>Not all Numpy slicing tricks may work for lists!

In [29]:
b[:,0]            # Error: list indices must be integers or slices, not tuple

TypeError: list indices must be integers or slices, not tuple

**NOTE**: Practice what you learned in this notebook with different arrays.